"""
    mpenum.py: This file contains the equivalent tables
                of enumerations defined in mpdev.dll
"""

#MP_TYPE
MP150 = 101
MP36 = 102
MP160 = 103
MP200 = 104
MP36A = 105

#MP_COM_TYPE
MPUSB = 10
MPUDP = 11

#TRIGGER_OPT
MPTRIGOFF = 1
MPTRIGEXT = 2
MPTRIGACH = 3
MPTRIGDCH = 4

#DIGITAL_OPT
SET_LOW_BITS = 1
SET_HIGH_BITS = 2
READ_LOW_BITS = 3
READ_HIGH_BITS = 4

#MP_RETURN_CODE
MPSUCCESS = 1
MPDRVERR = 2
MPDLLBUSY = 3
MPINVPARA = 4
MPNOTCON = 5
MPREADY = 6
MPWPRETRIG = 7
MPWTRIG = 8
MPBUSY = 9
MPNOACTCH = 10
MPCOMERR = 11
MPINVTYPE = 12
MPNOTINNET = 13
MPSMPLDLERR = 14
MPMEMALLOCERR = 15
MPSOCKERR = 16
MPUNDRFLOW = 17
MPPRESETERR = 18
MPPARSERERR = 19

# MP3XOUTPUT_OPT
OUTPUTVOLTAGELEVEL = 2
OUTPUTCHANNEL3 = 3
#OUTPUTSTIMULATOR = 4 # not supported with BHAPI 2.1
OUTPUTCHANNEL1 = 5
OUTPUTCHANNEL2 = 6
OUTPUTCHANNEL4 = 7
OUTPUTGROUND = 0x7f
